goldmark:
  renderer:
    unsafe: true
highlight:
  noClasses: false
  anchorLineNos: true
  codeFences: true
  guessSyntax: true
  lineNos: true
  style: dracula
  tabWidth: 2
tableOfContents:
  endLevel: 4
  ordered: true
  startLevel: 2
